/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hurtowniatowarow;

import java.awt.Color;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 * Klasa pokazująca koszyk z zamowionymi pprzez klienta towarami, umożliwiająca wykonanie zamówienia
 * @author Patryk
 */
public class Details extends javax.swing.JFrame {
    ArrayList<Towar> wyniki=new ArrayList<Towar>();
    Towar towar;
    Double suma=0.2;
    Integer i=0;
    int j=0;
    String login;
    /**
     * Konstruktor bezargumentowy na potrzeby testów
     */
    public Details() {
        initComponents();
        getContentPane().setBackground(new Color(70,160,250));
        setVisible(true);
        cena.setText("4 zł");
    }
    /**
     * Konstruktor dwuargumetowy bioracy liste towarów do zamówienia oraz login zamawiającego klienta
     * @param wyniki lista elementów do zamówienia
     * @param login  login zamawiającego klienta
     */
    public Details(ArrayList wyniki,String login) {
        initComponents();
        getContentPane().setBackground(new Color(70,160,250));
        setVisible(true);
        System.out.println("-------------DETAILS-------------");
        this.wyniki=wyniki;
        this.login=login;
        suma=Towar.oblicz_sume(wyniki);
        cena.setText(Double.toString(suma)+" zł");
        i=pokaz(i);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Lkoszyk = new javax.swing.JLabel();
        nazwa2 = new javax.swing.JLabel();
        ilosc1 = new javax.swing.JLabel();
        C1 = new javax.swing.JLabel();
        cena1 = new javax.swing.JLabel();
        nazwa1 = new javax.swing.JLabel();
        ilosc2 = new javax.swing.JLabel();
        cena2 = new javax.swing.JLabel();
        nazwa3 = new javax.swing.JLabel();
        ilosc3 = new javax.swing.JLabel();
        cena3 = new javax.swing.JLabel();
        nazwa4 = new javax.swing.JLabel();
        ilosc4 = new javax.swing.JLabel();
        cena4 = new javax.swing.JLabel();
        nazwa5 = new javax.swing.JLabel();
        ilosc5 = new javax.swing.JLabel();
        cena5 = new javax.swing.JLabel();
        podsumowanie = new javax.swing.JLabel();
        cena = new javax.swing.JLabel();
        zamawiam = new javax.swing.JButton();
        zamknij = new javax.swing.JButton();
        usun = new javax.swing.JButton();
        usun2 = new javax.swing.JButton();
        usun3 = new javax.swing.JButton();
        usun4 = new javax.swing.JButton();
        usun5 = new javax.swing.JButton();
        poprzedni = new javax.swing.JButton();
        nastepny = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Lkoszyk.setFont(new java.awt.Font("Times New Roman", 2, 14)); // NOI18N
        Lkoszyk.setText("Twoj koszyk:");

        nazwa2.setText("...");

        ilosc1.setText("...");

        cena1.setText("...");

        nazwa1.setText("...");

        ilosc2.setText("...");

        cena2.setText("...");

        nazwa3.setText("...");

        ilosc3.setText("...");

        cena3.setText("...");

        nazwa4.setText("...");

        ilosc4.setText("...");

        cena4.setText("...");

        nazwa5.setText("...");

        ilosc5.setText("...");

        cena5.setText("...");

        podsumowanie.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        podsumowanie.setText("Podsumowanie");

        cena.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        cena.setText("0.00 zł");

        zamawiam.setText("Zamawiam");
        zamawiam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                zamawiamActionPerformed(evt);
            }
        });

        zamknij.setText("Zamknij koszyk");
        zamknij.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                zamknijActionPerformed(evt);
            }
        });

        usun.setText("Usun");
        usun.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usunActionPerformed(evt);
            }
        });

        usun2.setText("Usun");
        usun2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usun2ActionPerformed(evt);
            }
        });

        usun3.setText("Usun");
        usun3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usun3ActionPerformed(evt);
            }
        });

        usun4.setText("Usun");
        usun4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usun4ActionPerformed(evt);
            }
        });

        usun5.setText("Usun");
        usun5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usun5ActionPerformed(evt);
            }
        });

        poprzedni.setText("Poprzednia");
        poprzedni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                poprzedniActionPerformed(evt);
            }
        });

        nastepny.setText("Nastepna");
        nastepny.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nastepnyActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(nazwa5, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(ilosc5, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(podsumowanie, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(ilosc2, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Lkoszyk, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(nazwa1, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(ilosc1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(cena1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(nazwa2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(nazwa3, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(nazwa4, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(ilosc3, javax.swing.GroupLayout.DEFAULT_SIZE, 43, Short.MAX_VALUE)
                                    .addComponent(ilosc4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(cena2, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(cena3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)
                                        .addComponent(cena4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(cena5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                        .addGap(9, 9, 9)))
                .addComponent(C1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(usun)
                    .addComponent(usun2)
                    .addComponent(usun3)
                    .addComponent(usun4)
                    .addComponent(usun5))
                .addGap(25, 25, 25))
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(zamknij, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(95, 95, 95)
                .addComponent(zamawiam, javax.swing.GroupLayout.DEFAULT_SIZE, 118, Short.MAX_VALUE)
                .addGap(33, 33, 33))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(poprzedni)
                        .addGap(18, 18, 18)
                        .addComponent(nastepny)
                        .addGap(32, 32, 32))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(cena, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(Lkoszyk, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(C1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(cena1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(ilosc1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(nazwa1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(usun))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ilosc2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nazwa2, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cena2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(usun2))
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nazwa3, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ilosc3, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cena3, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(usun3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nazwa4, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ilosc4)
                    .addComponent(cena4, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(usun4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nazwa5, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ilosc5)
                    .addComponent(cena5, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(usun5))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(poprzedni)
                    .addComponent(nastepny))
                .addGap(98, 98, 98)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(podsumowanie, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cena, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(zamawiam, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(zamknij, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    /**
     * Metoda wykonująca zamówienie przez klienta towaru z bazy
     * @param evt 
     */
    private void zamawiamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_zamawiamActionPerformed
        Connect p=new Connect();
        try {
            if(p.czy_uzupelnione(login) == true){
                p.makeOrder(wyniki,login);
            }
            else{
                JOptionPane.showMessageDialog(this, "Uzupelnij swoj profil w zakładce \nEdytuj profil aby mieć \nmożliwość zamawiania ze sklepu");
            }
        } catch (SQLException ex) {
            Logger.getLogger(Details.class.getName()).log(Level.SEVERE, null, ex);
        }
        Towar.removeAll(wyniki);
    }//GEN-LAST:event_zamawiamActionPerformed
    /**
     * Metoda zamykająca okno
     * @param evt 
     */
    private void zamknijActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_zamknijActionPerformed
        this.dispose();
    }//GEN-LAST:event_zamknijActionPerformed
    /**
     * Metoda przewijająca liste towarów wkoszyku do przodu
     * @param evt 
     */
    private void nastepnyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nastepnyActionPerformed
        int a=0;
        if(i%5==0){
            i=pokaz(i);
        }
    }//GEN-LAST:event_nastepnyActionPerformed
    /**
     * Metoda przewijająca liste towarów w koszyku do tyłu
     * @param evt 
     */
    private void poprzedniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_poprzedniActionPerformed
        int a=0;
        System.out.println("prev przed while i:"+i);
        if(i>4){
            i-=5;
            System.out.println("i%5="+(i%5));
            while( (i%5) != 0){
                System.out.println(i%5);
                i--;
            }
            System.out.println("prev po while i:"+i);
            i=pokaz(i);
            System.out.println("poprzedni PO WYJSCIU Z FUNKCJI i="+i);
        }
    }//GEN-LAST:event_poprzedniActionPerformed
    /**
     * Metoda pozwalająca usunać dany towar z koszyka zamówienia
     * @param evt 
     */
    private void usunActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usunActionPerformed
        Connect p=new Connect();
        int ktory=0;
        ktory=Towar.seek(wyniki,nazwa1.getText(),ilosc1.getText());
        try {
            wyniki.remove(ktory);
            p.removeFromBasket(nazwa1.getText(),ilosc1.getText());
            nazwa1.setForeground(Color.red);
            ilosc1.setForeground(Color.red);
            cena1.setForeground(Color.red);
        } catch (SQLException ex) {
            Logger.getLogger(Details.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_usunActionPerformed
    /**
     * Metoda pozwalająca usunać dany towar z koszyka zamówienia
     * @param evt 
     */
    private void usun2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usun2ActionPerformed
        Connect p=new Connect();
        int ktory=0;
        ktory=Towar.seek(wyniki,nazwa2.getText(),ilosc2.getText());
        try {
            wyniki.remove(ktory);
            p.removeFromBasket(nazwa2.getText(),ilosc2.getText());
            nazwa2.setForeground(Color.red);
            ilosc2.setForeground(Color.red);
            cena2.setForeground(Color.red);
        } catch (SQLException ex) {
            Logger.getLogger(Details.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_usun2ActionPerformed
    /**
     * Metoda pozwalająca usunać dany towar z koszyka zamówienia
     * @param evt 
     */
    private void usun3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usun3ActionPerformed
        Connect p=new Connect();
        int ktory=0;
        ktory=Towar.seek(wyniki,nazwa3.getText(),ilosc3.getText());
        try {
            wyniki.remove(ktory);
            p.removeFromBasket(nazwa3.getText(),ilosc3.getText());
            nazwa3.setForeground(Color.red);
            ilosc3.setForeground(Color.red);
            cena3.setForeground(Color.red);
        } catch (SQLException ex) {
            Logger.getLogger(Details.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_usun3ActionPerformed
    /**
     * Metoda pozwalająca usunać dany towar z koszyka zamówienia
     * @param evt 
     */
    private void usun4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usun4ActionPerformed
        Connect p=new Connect();
        int ktory=0;
        ktory=Towar.seek(wyniki,nazwa4.getText(),ilosc4.getText());
        try {
            wyniki.remove(ktory);
            p.removeFromBasket(nazwa4.getText(),ilosc4.getText());
            nazwa4.setForeground(Color.red);
            ilosc4.setForeground(Color.red);
            cena4.setForeground(Color.red);
        } catch (SQLException ex) {
            Logger.getLogger(Details.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_usun4ActionPerformed
    /**
     * Metoda pozwalająca usunać dany towar z koszyka zamówienia
     * @param evt 
     */
    private void usun5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usun5ActionPerformed
        Connect p=new Connect();
        int ktory=0;
        ktory=Towar.seek(wyniki,nazwa5.getText(),ilosc5.getText());
        try {
            wyniki.remove(ktory);
            p.removeFromBasket(nazwa5.getText(),ilosc5.getText());
            nazwa5.setForeground(Color.red);
            ilosc5.setForeground(Color.red);
            cena5.setForeground(Color.red);
        } catch (SQLException ex) {
            Logger.getLogger(Details.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_usun5ActionPerformed

    //--------------------------------------------------------------------------
    /**
     * Metoda wstawiająca towary z koszyka do etykiet i pol tekstowych 
     * @param i
     * @return 
     */
    public Integer pokaz(Integer i){   
        int a=0;
        System.out.println("pokaz() i="+i+", i%5="+(i%5));
        for(a=0;i<wyniki.size() && a<5;i++,a++){
            if(i%5==0 && wyniki.size()!=0){
                nazwa1.setText(wyniki.get(i).nazwa);
                ilosc1.setText(wyniki.get(i).ilosc);
                cena1.setText(wyniki.get(i).cena);
                ilosc1.setVisible(true);
                cena1.setVisible(true);
                nazwa1.setVisible(true);
                usun.setVisible(true);
                //i++;
                //a++;
            }
            if(i%5==1){
                nazwa2.setText(wyniki.get(i).nazwa);
                ilosc2. setText(wyniki.get(i).ilosc);
                cena2.setText(wyniki.get(i).cena);
                ilosc2.setVisible(true);
                usun2.setVisible(true);
                cena2.setVisible(true);
                nazwa2.setVisible(true);
                //i++;
                //a++;
            }
            if(i%5==2){
                nazwa3.setText(wyniki.get(i).nazwa);
                ilosc3.setText(wyniki.get(i).ilosc);
                cena3.setText(wyniki.get(i).cena);
                ilosc3.setVisible(true);
                usun3.setVisible(true);
                cena3.setVisible(true);
                nazwa3.setVisible(true);
                //i++;
                //a++;
            }
            if(i%5==3){
                nazwa4.setText(wyniki.get(i).nazwa);
                ilosc4.setText(wyniki.get(i).ilosc);
                cena4.setText(wyniki.get(i).cena);
                ilosc4.setVisible(true);
                usun4.setVisible(true);
                cena4.setVisible(true);
                nazwa4.setVisible(true);
                //i++;
               // a++;
            }
            if(i%5==4){
                nazwa5.setText(wyniki.get(i).nazwa);
                ilosc5.setText(wyniki.get(i).ilosc);
                cena5.setText(wyniki.get(i).cena);
                ilosc5.setVisible(true);
                usun5.setVisible(true);
                cena5.setVisible(true);
                nazwa5.setVisible(true);
               // i++;
               // a++;
            }
            //System.out.println("PO pokaz() i="+i);;
        }
        System.out.println("PO pokaz() i="+i+" ,a= "+a);
        for(;a<5;a++){
                if(a==0){
                    ilosc1.setVisible(false);
                    usun.setVisible(false);
                    cena1.setVisible(false);
                    nazwa1.setVisible(false);
                }
                if(a==1){
                    ilosc2.setVisible(false);
                    usun2.setVisible(false);
                    cena2.setVisible(false);
                    nazwa2.setVisible(false);
                }
                 if(a==2){
                    ilosc3.setVisible(false);
                    usun3.setVisible(false);
                    cena3.setVisible(false);
                    nazwa3.setVisible(false);
                }
                  if(a==3){
                    ilosc4.setVisible(false);
                    usun4.setVisible(false);
                    cena4.setVisible(false);
                    nazwa4.setVisible(false);
                }
                   if(a==4){
                    ilosc5.setVisible(false);
                    usun5.setVisible(false);
                    cena5.setVisible(false);
                    nazwa5.setVisible(false);
                }
            }
        return i;
    }
    //--------------------------------------------------------------------------
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Details.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Details.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Details.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Details.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Details().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel C1;
    private javax.swing.JLabel Lkoszyk;
    private javax.swing.JLabel cena;
    private javax.swing.JLabel cena1;
    private javax.swing.JLabel cena2;
    private javax.swing.JLabel cena3;
    private javax.swing.JLabel cena4;
    private javax.swing.JLabel cena5;
    private javax.swing.JLabel ilosc1;
    private javax.swing.JLabel ilosc2;
    private javax.swing.JLabel ilosc3;
    private javax.swing.JLabel ilosc4;
    private javax.swing.JLabel ilosc5;
    private javax.swing.JButton nastepny;
    private javax.swing.JLabel nazwa1;
    private javax.swing.JLabel nazwa2;
    private javax.swing.JLabel nazwa3;
    private javax.swing.JLabel nazwa4;
    private javax.swing.JLabel nazwa5;
    private javax.swing.JLabel podsumowanie;
    private javax.swing.JButton poprzedni;
    private javax.swing.JButton usun;
    private javax.swing.JButton usun2;
    private javax.swing.JButton usun3;
    private javax.swing.JButton usun4;
    private javax.swing.JButton usun5;
    private javax.swing.JButton zamawiam;
    private javax.swing.JButton zamknij;
    // End of variables declaration//GEN-END:variables
}
