/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hurtowniatowarow;

import java.awt.Color;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
/**
 * Klasa umozliwiająca edycje profilu dla zalogowanego klienta
 * @author Mati
 */
public class Edycjaprofilu extends javax.swing.JFrame {
    String login;
    String haslo;
    String imie;
    String nazwisko;
    String email;
    String nrdomu;
    String ulica;
    String miejscowosc;
    String wojewodztwo;
    String kraj;
    //przykladowo dalem
    String[] tablica = new String[9];
    Integer idklienta=1;
    String[] wyniki = new String[9];
    Connect aktualizuj = new Connect();
    Integer i;
    String mojLogin="";
    JFrame stareOkno;
    
    
  
    
    
    

    /**
     * Konstruktor bezargumentowy na potrzeby testów
     */
    public Edycjaprofilu() {
        //wczyt srtarych danych
        this.setVisible(true);
        initComponents();
        getContentPane().setBackground(new Color(70,160,250));
    }
    /**
     * Konstruktor dwuargumentowy przyjmujący uchwyt do okna rodzica oraz login zalogowanego klienta
     * @param stareOkno uchwyt do okna rodzica
     * @param log login zalogowanego klienta
     * @throws SQLException 
     */
     public Edycjaprofilu(JFrame stareOkno,String log) throws SQLException {
        //wczyt srtarych danych
        initComponents();
        this.setVisible(true);
        getContentPane().setBackground(new Color(70,160,250));
        Connect aktualizacja = new Connect();
        wyniki=aktualizacja.fillField(log);
        tHaslo.setText(wyniki[0]);
        tImie.setText(wyniki[1]);
        tNazwisko.setText(wyniki[2]);
        tEmail.setText(wyniki[3]);
        tNrdomu.setText(wyniki[4]);
        tUlica.setText(wyniki[5]);
        tMiejscowosc.setText(wyniki[6]);
        tWojewodztwo.setText(wyniki[7]);
        tKraj.setText(wyniki[8]);
        
        this.stareOkno=stareOkno;
        mojLogin=log;
     }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bWroc = new javax.swing.JButton();
        tHaslo = new javax.swing.JTextField();
        tImie = new javax.swing.JTextField();
        tNazwisko = new javax.swing.JTextField();
        tEmail = new javax.swing.JTextField();
        tNrdomu = new javax.swing.JTextField();
        tUlica = new javax.swing.JTextField();
        tMiejscowosc = new javax.swing.JTextField();
        tWojewodztwo = new javax.swing.JTextField();
        tKraj = new javax.swing.JTextField();
        bAktualizuj = new javax.swing.JButton();
        laHaslo = new javax.swing.JLabel();
        laImie = new javax.swing.JLabel();
        laNazwisko = new javax.swing.JLabel();
        laEmail = new javax.swing.JLabel();
        laNrdomu = new javax.swing.JLabel();
        laUlica = new javax.swing.JLabel();
        laMiejscowosc = new javax.swing.JLabel();
        laWojewodztwo = new javax.swing.JLabel();
        laKraj = new javax.swing.JLabel();
        laInformacja = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        bWroc.setText("Wróć");
        bWroc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bWrocActionPerformed(evt);
            }
        });

        bAktualizuj.setText("Aktualizuj");
        bAktualizuj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bAktualizujActionPerformed(evt);
            }
        });

        laHaslo.setText("Hasło:");

        laImie.setText("Imię:");

        laNazwisko.setText("Nazwisko:");

        laEmail.setText("Email:");

        laNrdomu.setText("Nr domu:");

        laUlica.setText("Ulica:");

        laMiejscowosc.setText("Miejscowość:");

        laWojewodztwo.setText("Województwo:");

        laKraj.setText("Kraj:");

        laInformacja.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        laInformacja.setForeground(new java.awt.Color(255, 0, 0));
        laInformacja.setText("Informacja");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(bWroc)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(laHaslo)
                            .addComponent(laImie)
                            .addComponent(laNazwisko)
                            .addComponent(laEmail)
                            .addComponent(laNrdomu)
                            .addComponent(laUlica)
                            .addComponent(laMiejscowosc)
                            .addComponent(laWojewodztwo)
                            .addComponent(laKraj))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tKraj, javax.swing.GroupLayout.DEFAULT_SIZE, 210, Short.MAX_VALUE)
                            .addComponent(tWojewodztwo)
                            .addComponent(tMiejscowosc)
                            .addComponent(tUlica)
                            .addComponent(tNrdomu)
                            .addComponent(tEmail)
                            .addComponent(tNazwisko)
                            .addComponent(tImie)
                            .addComponent(tHaslo))
                        .addGap(50, 50, 50))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(laInformacja)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 155, Short.MAX_VALUE)
                        .addComponent(bAktualizuj)
                        .addGap(42, 42, 42))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(bWroc)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 126, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tHaslo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(laHaslo))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tImie, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(laImie))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tNazwisko, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(laNazwisko))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(laEmail))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tNrdomu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(laNrdomu))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tUlica, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(laUlica))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tMiejscowosc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(laMiejscowosc))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tWojewodztwo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(laWojewodztwo))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tKraj, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(laKraj))
                        .addGap(18, 18, 18)
                        .addComponent(laInformacja))
                    .addComponent(bAktualizuj))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    /**
     * Metoda pobierająca nowe dane do aktualizacji i wykonująca aktualizacje
     * @param evt 
     */
    private void bAktualizujActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bAktualizujActionPerformed
        boolean po=false;
        haslo=tHaslo.getText();
        imie=tImie.getText();
        nazwisko=tNazwisko.getText();
        email=tEmail.getText();
        nrdomu=tNrdomu.getText();
        ulica=tUlica.getText();
        miejscowosc=tMiejscowosc.getText();
        wojewodztwo=tWojewodztwo.getText();
        kraj=tKraj.getText();
        String[] tab2=new String[9];
        tab2[0]=haslo;
        tab2[1]=imie;
        tab2[2]=nazwisko;
        tab2[3]=email;
        tab2[4]=nrdomu;
        tab2[5]=ulica;
        tab2[6]=miejscowosc;
        tab2[7]=wojewodztwo;
        tab2[8]=kraj;
        boolean czy_wypelnione=true;
        for(int r=0;r<9;r++){
            if(tab2[r].equals("") && r!=7){
                czy_wypelnione=false;
            }
        }
        if(czy_wypelnione==false){
             laInformacja.setText("Nie wypełniono poprawnie pól");
        }
        else{
            try {
                po=aktualizuj.updateMyData(mojLogin,tab2);
            } catch (SQLException ex) {
                Logger.getLogger(Edycjaprofilu.class.getName()).log(Level.SEVERE, null, ex);
            }
            if(po ==true){
                laInformacja.setText("Aktualizacja przebiegla pomyslnie");
            }
            else{
                laInformacja.setText("Problemy z baza. Przepraszamy");
            }
        }
    }//GEN-LAST:event_bAktualizujActionPerformed
    /**
     * Metoda pozwala na powrót do poprzedniego okna
     * @param evt 
     */
    private void bWrocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bWrocActionPerformed
        this.dispose();
        stareOkno.setVisible(true);
    }//GEN-LAST:event_bWrocActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Edycjaprofilu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Edycjaprofilu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Edycjaprofilu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Edycjaprofilu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Edycjaprofilu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bAktualizuj;
    private javax.swing.JButton bWroc;
    private javax.swing.JLabel laEmail;
    private javax.swing.JLabel laHaslo;
    private javax.swing.JLabel laImie;
    private javax.swing.JLabel laInformacja;
    private javax.swing.JLabel laKraj;
    private javax.swing.JLabel laMiejscowosc;
    private javax.swing.JLabel laNazwisko;
    private javax.swing.JLabel laNrdomu;
    private javax.swing.JLabel laUlica;
    private javax.swing.JLabel laWojewodztwo;
    private javax.swing.JTextField tEmail;
    private javax.swing.JTextField tHaslo;
    private javax.swing.JTextField tImie;
    private javax.swing.JTextField tKraj;
    private javax.swing.JTextField tMiejscowosc;
    private javax.swing.JTextField tNazwisko;
    private javax.swing.JTextField tNrdomu;
    private javax.swing.JTextField tUlica;
    private javax.swing.JTextField tWojewodztwo;
    // End of variables declaration//GEN-END:variables
}
