package hurtowniatowarow;

import java.awt.Color;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
/**
 * Klasa podstawowa dla aplkacji od której zaczyna ona działanie 
 * @author Patryk
 */
public class MainWindow extends javax.swing.JFrame {

    /**
     * Konstruktor bezargumentowy wywołujący okno poczatkowe
     */
    public MainWindow() {
        initComponents();
        getContentPane().setBackground(new Color(70,160,250));
        setResizable(false);
        setVisible(true);
    }
    /**
     * Konstruktor jednoargumentowy wywołujący okno poczatkowe
     * @param i 
     */
    public MainWindow(int i) {
        initComponents();
        getContentPane().setBackground(new Color(70,160,250));
        setResizable(false);
        setVisible(true);
        JOptionPane.showMessageDialog(this, "Rejestracja zakończona sukcesem");
    }
        
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        zaloguj = new javax.swing.JButton();
        zarejestruj = new javax.swing.JButton();
        opcje = new javax.swing.JButton();
        zamknij = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        zaloguj.setText("Zaloguj sie");
        zaloguj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                zalogujActionPerformed(evt);
            }
        });

        zarejestruj.setText("Zarejestruj sie");
        zarejestruj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                zarejestrujActionPerformed(evt);
            }
        });

        opcje.setText("Opcje");

        zamknij.setText("Zamknij");
        zamknij.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                zamknijActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(93, 93, 93)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(zamknij, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(zarejestruj, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(zaloguj, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(opcje, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(111, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(94, 94, 94)
                .addComponent(zaloguj, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(zarejestruj, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addComponent(opcje, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addComponent(zamknij, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(192, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    /**
     * Metoda wywołujaca konstruktor klasy LogForm po udanym sprawdzeniu loginu i hasła
     * @param evt 
     */
    private void zalogujActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_zalogujActionPerformed
        //Connect okno1=new Connect();
        JFrame jf = this; 
        jf.setVisible(false);
        LogForm okno1=new LogForm(jf);
    }//GEN-LAST:event_zalogujActionPerformed
    /**
     * Metoda wywołująca konstruktor klasy Rejestracja na potrzeby nowych klientów
     * @param evt 
     */
    private void zarejestrujActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_zarejestrujActionPerformed
        JFrame rodzic=this;
        this.setVisible(false);
        Rejestracja okno_rejestr = new Rejestracja(rodzic);
    }//GEN-LAST:event_zarejestrujActionPerformed
    /**
     * Metoda zamykająca aplikcje
     * @param evt 
     */
    private void zamknijActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_zamknijActionPerformed
        this.dispose();
    }//GEN-LAST:event_zamknijActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainWindow().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton opcje;
    private javax.swing.JButton zaloguj;
    private javax.swing.JButton zamknij;
    private javax.swing.JButton zarejestruj;
    // End of variables declaration//GEN-END:variables
}
